// Títulos reales de Wikipedia por ciudad/monumento (fallback para fotos libres),
// reimplementado del prototipo (assets/atlas.js, const WIKI).
export const WIKI_TITLES = {
  londres: {
    'Big Ben y Parlamento': ['es::Big Ben', 'en::Big Ben'],
    'Abadía de Westminster': ['es::Abadía de Westminster', 'en::Westminster Abbey'],
    'Palacio de Buckingham': ['es::Palacio de Buckingham', 'en::Buckingham Palace'],
    'London Eye': ['es::London Eye', 'en::London Eye'],
    'Trafalgar Square': ['es::Trafalgar Square', 'en::Trafalgar Square'],
    'Covent Garden': ['es::Covent Garden', 'en::Covent Garden'],
    'Piccadilly Circus': ['es::Piccadilly Circus', 'en::Piccadilly Circus'],
    'British Museum': ['es::Museo Británico', 'en::British Museum'],
    'Catedral de St. Paul': ['es::Catedral de San Pablo (Londres)', "en::St Paul's Cathedral"],
    'Torre de Londres': ['es::Torre de Londres', 'en::Tower of London'],
  },
  paris: {
    'Torre Eiffel': ['es::Torre Eiffel', 'en::Eiffel Tower'],
    'Arco del Triunfo': ['es::Arco de Triunfo (París)', 'en::Arc de Triomphe'],
    'Champs-Élysées': ['es::Campos Elíseos', 'en::Champs-Élysées'],
    'Museo del Louvre': ['es::Museo del Louvre', 'en::Louvre'],
    'Museo de Orsay': ['es::Museo de Orsay', "en::Musée d'Orsay"],
    'Notre-Dame': ['es::Catedral de Notre Dame', 'en::Notre-Dame de Paris'],
    'Sainte-Chapelle': ['es::Sainte-Chapelle', 'en::Sainte-Chapelle'],
    'Sacré-Cœur': ['es::Basílica del Sagrado Corazón (París)', 'en::Sacré-Cœur, Paris'],
    'Le Marais': ['es::Le Marais', 'en::Le Marais'],
    'Panteón': ['es::Panteón de París', 'en::Panthéon'],
  },
  bruselas: {
    'Grand-Place': ['es::Grand Place (Bruselas)', 'en::Grand-Place'],
    'Manneken Pis': ['es::Manneken Pis', 'en::Manneken Pis'],
    'Galerías Saint-Hubert': ['es::Galerías Reales de San Huberto', 'en::Galeries Royales Saint-Hubert'],
    'Catedral de San Miguel': ['es::Catedral de San Miguel y Santa Gúdula', 'en::Cathedral of St. Michael and St. Gudula'],
    'Atomium': ['es::Atomium', 'en::Atomium'],
    'Parque del Cincuentenario': ['es::Parque del Cincuentenario', 'en::Cinquantenaire'],
  },
  roma: {
    'Coliseo': ['es::Coliseo', 'en::Colosseum'],
    'Foro Romano': ['es::Foro Romano', 'en::Roman Forum'],
    'Fontana di Trevi': ['es::Fontana di Trevi', 'en::Trevi Fountain'],
    'Panteón': ['es::Panteón de Agripa', 'en::Pantheon, Rome'],
    'Piazza Navona': ['es::Plaza Navona', 'en::Piazza Navona'],
    'Basílica de San Pedro': ['es::Basílica de San Pedro', "en::St. Peter's Basilica"],
    "Castel Sant'Angelo": ["es::Castillo Sant'Angelo", "en::Castel Sant'Angelo"],
    'Plaza de España': ['es::Plaza de España (Roma)', 'en::Spanish Steps'],
    'Trastevere': ['es::Trastevere', 'en::Trastevere'],
  },
  madrid: {
    'Palacio Real': ['es::Palacio Real de Madrid', 'en::Royal Palace of Madrid'],
    'Plaza Mayor': ['es::Plaza Mayor de Madrid', 'en::Plaza Mayor, Madrid'],
    'Puerta del Sol': ['es::Puerta del Sol', 'en::Puerta del Sol'],
    'Museo del Prado': ['es::Museo del Prado', 'en::Museo del Prado'],
    'Parque del Retiro': ['es::Parque del Retiro', 'en::Buen Retiro Park'],
    'Reina Sofía': ['es::Museo Reina Sofía', 'en::Museo Reina Sofía'],
    'Gran Vía': ['es::Gran Vía (Madrid)', 'en::Gran Vía'],
    'Plaza de Cibeles': ['es::Plaza de Cibeles', 'en::Plaza de Cibeles'],
    'Mercado de San Miguel': ['es::Mercado de San Miguel', 'en::Mercado de San Miguel'],
    'La Latina': ['es::La Latina (Madrid)', 'en::La Latina (Madrid)'],
  },
}
